<?php

namespace steevanb\DoctrineReadOnlyHydrator\Hydrator;

use Doctrine\Common\Proxy\ProxyGenerator;
use Doctrine\ORM\Mapping\ClassMetadata;
use steevanb\DoctrineReadOnlyHydrator\Entity\ReadOnlyEntityInterface;
use steevanb\DoctrineReadOnlyHydrator\Exception\DefaultValueCantBeRenderedException;
use steevanb\DoctrineReadOnlyHydrator\Exception\PrivateMethodShouldNotAccessPropertiesException;

class ReadOnlyHydrator extends SimpleObjectHydrator
{
    const HYDRATOR_NAME = 'readOnly';

    /** @var string[] */
    protected $proxyFilePathsCache = [];

    /** @var string[] */
    protected $proxyNamespacesCache = [];

    /** @var string[] */
    protected $proxyClassNamesCache = [];

    /**
     * @param ClassMetadata $classMetaData
     * @param array $data
     * @return mixed
     * @throws \Exception
     */
    protected function createEntity(ClassMetadata $classMetaData, array $data): mixed
    {
        $className = $this->getEntityClassName($classMetaData, $data);
        $this->generateProxyFile($classMetaData, $data);

        require_once($this->getProxyFilePath($className));
        $proxyClassName = $this->getProxyNamespace($className) . '\\' . $this->getProxyClassName($className);
        $entity = new $proxyClassName(array_keys($data));

        $this->deferPostLoadInvoking($classMetaData, $entity);

        return $entity;
    }

    /**
     * @param ClassMetadata $classMetaData
     * @param array $data
     * @return $this
     */
    protected function generateProxyFile(ClassMetadata $classMetaData, array $data): self
    {
        $entityClassName = $this->getEntityClassName($classMetaData, $data);
        $proxyFilePath = $this->getProxyFilePath($entityClassName);
        if (file_exists($proxyFilePath) === false) {
            $proxyMethodsCode = implode("\n\n", $this->getPhpForProxyMethods($classMetaData, $entityClassName));
            $proxyNamespace = $this->getProxyNamespace($entityClassName);
            $proxyClassName = $this->getProxyClassName($entityClassName);
            $generator = static::class;
            $readOnlyInterface = ReadOnlyEntityInterface::class;

            $php = <<<PHP
<?php

namespace $proxyNamespace;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY $generator
 */
class $proxyClassName extends \\$entityClassName implements \\$readOnlyInterface
{
    protected \$loadedProperties;

    public function __construct(array \$loadedProperties)
    {
        \$this->loadedProperties = \$loadedProperties;
    }

$proxyMethodsCode

    public function isReadOnlyPropertiesLoaded(array \$properties)
    {
        \$return = true;
        foreach (\$properties as \$property) {
            if (in_array(\$property, \$this->loadedProperties) === false) {
                \$return = false;
                break;
            }
        }

        return \$return;
    }

    public function assertReadOnlyPropertiesAreLoaded(array \$properties)
    {
        foreach (\$properties as \$property) {
            if (in_array(\$property, \$this->loadedProperties) === false) {
                throw new \steevanb\DoctrineReadOnlyHydrator\Exception\PropertyNotLoadedException(\$this, \$property);
            }
        }
    }
}
PHP;
            file_put_contents($proxyFilePath, $php);
        }

        return $this;
    }

    /**
     * @param string $entityClassName
     * @return string
     */
    public function getProxyFilePath($entityClassName): string
    {
        if (isset($this->proxyFilePathsCache[$entityClassName]) === false) {
            $fileName = str_replace('\\', '_', $entityClassName) . '.php';
            $this->proxyFilePathsCache[$entityClassName] = $this->getProxyDirectory() . DIRECTORY_SEPARATOR . $fileName;
        }

        return $this->proxyFilePathsCache[$entityClassName];
    }

    /**
     * @param string $entityClassName
     * @return string
     */
    protected function getProxyNamespace($entityClassName): string
    {
        if (isset($this->proxyNamespacesCache[$entityClassName]) === false) {
            $this->proxyNamespacesCache[$entityClassName] =
                'ReadOnlyProxies\\' . substr($entityClassName, 0, strrpos($entityClassName, '\\'));
        }

        return $this->proxyNamespacesCache[$entityClassName];
    }

    /**
     * @param string $entityClassName
     * @return string
     */
    protected function getProxyClassName($entityClassName): string
    {
        if (isset($this->proxyClassNamesCache[$entityClassName]) === false) {
            $this->proxyClassNamesCache[$entityClassName] =
                substr($entityClassName, strrpos($entityClassName, '\\') + 1);
        }

        return $this->proxyClassNamesCache[$entityClassName];
    }

    /**
     * As Doctrine\ORM\EntityManager::newHydrator() call new FooHydrator($this), we can't set parameters to Hydrator.
     * So, we will use proxyDirectory from Doctrine\Common\Proxy\AbstractProxyFactory.
     * It's directory used by Doctrine\ORM\Internal\Hydration\ObjectHydrator.
     *
     * @return string
     */
    protected function getProxyDirectory(): string
    {
        /** @var ProxyGenerator $proxyGenerator */
        $proxyGenerator = $this->getPrivatePropertyValue($this->_em->getProxyFactory(), 'proxyGenerator');

        $directory = $this->getPrivatePropertyValue($proxyGenerator, 'proxyDirectory');
        $readOnlyDirectory = $directory . DIRECTORY_SEPARATOR . 'ReadOnly';
        if (is_dir($readOnlyDirectory) === false) {
            mkdir($readOnlyDirectory, 0775, true);
        }

        return $readOnlyDirectory;
    }

    /**
     * @param \ReflectionMethod $reflectionMethod
     * @param array $properties
     * @return array
     */
    protected function getUsedProperties(\ReflectionMethod $reflectionMethod, $properties): array
    {
        $classLines = file($reflectionMethod->getFileName());
        $methodLines = array_slice(
            $classLines,
            $reflectionMethod->getStartLine() - 1,
            $reflectionMethod->getEndLine() - $reflectionMethod->getStartLine() + 1
        );
        $code = '<?php' . "\n" . implode("\n", $methodLines) . "\n" . '?>';

        $return = [];
        $nextStringIsProperty = false;
        foreach (token_get_all($code) as $token) {
            if (is_array($token)) {
                if ($token[0] === T_VARIABLE && $token[1] === '$this') {
                    $nextStringIsProperty = true;
                } elseif ($nextStringIsProperty && $token[0] === T_STRING) {
                    $nextStringIsProperty = false;
                    if (in_array($token[1], $properties)) {
                        $return[$token[1]] = true;
                    }
                }
            }
        }

        return array_keys($return);
    }

    /**
     * @param ClassMetadata $classMetaData
     * @param string $entityClassName
     * @return array
     * @throws PrivateMethodShouldNotAccessPropertiesException
     */
    protected function getPhpForProxyMethods(ClassMetadata $classMetaData, $entityClassName): array
    {
        $return = [];
        $reflectionClass = new \ReflectionClass($entityClassName);
        $properties = array_merge($classMetaData->getFieldNames(), array_keys($classMetaData->associationMappings));
        foreach ($reflectionClass->getMethods() as $method) {
            if ($method->name === '__construct') {
                continue;
            }

            $usedProperties = $this->getUsedProperties($method, $properties);
            if (count($usedProperties) > 0) {
                if ($method->isPrivate()) {
                    throw new PrivateMethodShouldNotAccessPropertiesException(
                        $entityClassName,
                        $method->name,
                        $usedProperties
                    );
                }

                $return[] = $this->getPhpForMethod($method, $usedProperties);
            }
        }

        return $return;
    }

    /**
     * @param \ReflectionMethod $reflectionMethod
     * @param array $properties
     * @return string
     */
    protected function getPhpForMethod(\ReflectionMethod $reflectionMethod, array $properties): string
    {
        $signature = ($reflectionMethod->isPublic()) ? 'public' : 'protected';
        $signature .= ' function ' . $reflectionMethod->name . '(';
        $parameters = [];
        foreach ($reflectionMethod->getParameters() as $parameter) {
            $parameters[] = $this->getPhpForParameter($parameter);
        }
        $signature .= implode(', ', $parameters) . ')';

        $method = $reflectionMethod->name;

        array_walk($properties, function(&$name) {
            $name = "'" . $name . "'";
        });
        $propertiesToAssert = implode(', ', $properties);

        $reflectionReturnType = $reflectionMethod->getReturnType();
        if ($reflectionReturnType instanceof \ReflectionType) {
            if (
                $reflectionReturnType instanceof \ReflectionNamedType
                && $reflectionReturnType->getName() === 'parent'
            ) {
                throw new \Exception('Function with return type parent can\'t be overloaded.');
            }

            $returnType = $this->getPhpForType($reflectionReturnType, $reflectionMethod->getDeclaringClass());
            $signature .= ': ' . $returnType;
            // void et never interdisent tous les deux "return <expression>;"
            $returnKeyWord = \in_array($returnType, ['void', 'never'], true) ? null : 'return ';
        } else {
            $returnKeyWord = 'return ';
        }

        $php = <<<PHP
    $signature
    {
        \$this->assertReadOnlyPropertiesAreLoaded(array($propertiesToAssert));

        {$returnKeyWord}parent::{$method}(...func_get_args());
    }
PHP;

        return $php;
    }

    /**
     * @param \ReflectionParameter $parameter
     * @return string
     */
    protected function getPhpForParameter(\ReflectionParameter $parameter): string
    {
        $php = null;
        $type = $parameter->getType();
        if ($type instanceof \ReflectionType) {
            $php .= $this->getPhpForType($type, $parameter->getDeclaringClass()) . ' ';
        }

        if ($parameter->isPassedByReference()) {
            $php .= '&';
        }
        if ($parameter->isVariadic()) {
            $php .= '...';
        }
        $php .= '$' . $parameter->name;

        if ($parameter->isVariadic() === false && $parameter->isDefaultValueAvailable()) {
            $php .= ' = ' . $this->getPhpForDefaultValue($parameter);
        }

        return $php;
    }

    protected function getPhpForType(\ReflectionType $reflectionType, \ReflectionClass $declaringClass): string
    {
        if ($reflectionType instanceof \ReflectionUnionType) {
            return implode('|', array_map(
                function (\ReflectionType $subType) use ($declaringClass): string {
                    $php = $this->getPhpForType($subType, $declaringClass);

                    return ($subType instanceof \ReflectionIntersectionType) ? '(' . $php . ')' : $php;
                },
                $reflectionType->getTypes()
            ));
        }

        if ($reflectionType instanceof \ReflectionIntersectionType) {
            return implode('&', array_map(
                fn (\ReflectionType $subType): string => $this->getPhpForType($subType, $declaringClass),
                $reflectionType->getTypes()
            ));
        }

        if ($reflectionType instanceof \ReflectionNamedType === false) {
            return static::extractNameFromReflexionType($reflectionType);
        }

        $name = $reflectionType->getName();
        // mixed et null acceptent déjà null, les préfixer de ? est une erreur de compilation
        $nullable = $reflectionType->allowsNull() && $name !== 'mixed' && $name !== 'null';

        if ($reflectionType->isBuiltin() || $name === 'static') {
            return ($nullable ? '?' : '') . $name;
        }

        switch ($name) {
            case 'self':
                $name = $declaringClass->getName();
                break;
            case 'parent':
                $name = $declaringClass->getParentClass()->getName();
                break;
        }

        return ($nullable ? '?' : '') . $this->getFullQualifiedClassName($name);
    }

    protected function getPhpForDefaultValue(\ReflectionParameter $parameter): string
    {
        if ($parameter->isDefaultValueConstant() === false) {
            return $this->getPhpForValue($parameter->getDefaultValue());
        }

        $constantName = $parameter->getDefaultValueConstantName();
        $className = strstr($constantName, '::', true);
        if (\is_string($className)) {
            // self, static et parent restent valides dans le proxie, qui hérite de l'entité
            return \in_array($className, ['self', 'static', 'parent'], true)
                ? $constantName
                : $this->getFullQualifiedClassName($constantName);
        }

        // une constante globale est rendue résolue dans le namespace de déclaration, où elle n'existe
        // pas forcément : seul le nom court, soumis au repli global, est alors valide dans le proxie
        return \defined($constantName)
            ? $this->getFullQualifiedClassName($constantName)
            : ltrim(strrchr('\\' . $constantName, '\\'), '\\');
    }

    protected function getPhpForValue(mixed $value): string
    {
        if ($value === null) {
            return 'null';
        }
        if (\is_bool($value)) {
            return ($value === true) ? 'true' : 'false';
        }
        if ($value instanceof \UnitEnum) {
            return var_export($value, true);
        }
        // var_export rendrait un ObjetQuelconque::__set_state(), qui n'est pas une expression
        // constante : le proxie ne compilerait pas, et generateProxyFile() ne le réécrit jamais
        if (\is_object($value)) {
            throw new DefaultValueCantBeRenderedException($value);
        }
        if (\is_array($value) === false) {
            return var_export($value, true);
        }

        $isList = array_is_list($value);
        $items = [];
        foreach ($value as $key => $item) {
            $items[] = $isList
                ? $this->getPhpForValue($item)
                : var_export($key, true) . ' => ' . $this->getPhpForValue($item);
        }

        return '[' . implode(', ', $items) . ']';
    }

    /**
     * PHP7 Reflection sometimes return \Foo\Bar, sometimes Foo\Bar
     * @param string $className
     * @return string
     */
    protected function getFullQualifiedClassName($className): string
    {
        return '\\' . ltrim($className, '\\');
    }

    /**
     * @param \ReflectionType $reflectionType
     * @return string
     * @see https://github.com/symfony/symfony/blob/v3.2.6/src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php#L215
     */
    protected static function extractNameFromReflexionType(\ReflectionType $reflectionType): string
    {
        return $reflectionType instanceof \ReflectionNamedType
            ? $reflectionType->getName()
            : $reflectionType->__toString();
    }
}
